### ISSUE TITLE
Allow multiple command/message in one handler

### ISSUE THREAD

**Issue by Folleach** [Folleach/DonationAlerts-Minecraft#5]
For avoid boilerplate
```
handlers:
- delay: 0
  properties:
    type: daintegrate/handler/message
    value:
      message: Hello! This is an example message for all events from Donation Alerts
- delay: 0
  properties:
    type: daintegrate/handler/message
    value:
      message: Hello! This is an example message for all events from Donation Alerts
 ```
